apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: m2a-backend-ingress
  namespace: m2a-backend

spec:
  rules:
    - host: m2a.jaipasraisonla.team
      http:
        paths:
          - path: /back
            pathType: Prefix
            backend:
              service:
                name: m2a-backend
                port:
                  name: web